name: Android CI - Build APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:                 # ← indentation correcte (2 espaces après 'jobs:')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build with Gradle
        run: ./gradlew :app:assembleDebug   # ou :ScanneurTableauApp:assembleDebug selon ton module

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ScannerTableauPro
          path: app/build/outputs/apk/debug/*.apk
